version: '3.8'

services:
  buyblack-city-guide:
    build: .
    ports:
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
    volumes:
      - ./city_explorer/data:/app/city_explorer/data
    restart: unless-stopped

